### ISSUE TITLE
copyright

### ISSUE THREAD

**Issue by 3kh0** [ZombieDuck2309/ZombieDuck2309.github.io#1]
Hello there!

I have looked through your GitHub repo and I found some things that I believe were taken from my site. I ask that you take them down to respect my work and what I do.
If the original one was blocked then you can contact me and I can give you more links. If you have any questions please feel free to reach out to me!

Thanks!
Echo

**Comment by ZombieDuck2309** [comment]
if you had gone to the website you can see that im not using any of your code anymore. I did use to use yours but after i learned web development, i am making my own version of the site. I will delete your files as i have forgotten too, but just so yk Im not using your code anymore.
